name: SOLARIS SPORTS
favicon: null
layout_spectrum: 0.75723
typography_spectrum: 0.38672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1540572156663984
  lightness: 0.6875
  saturation: 0.8705006674863398
  rhythmicContrast: 0.6438543747644871
purpose: []
